ipc = true
splash = false

wallpaper {
    monitor = DP-6
    path = /home/sergio/Documents/wallpaper
    fit_mode = cover
    timeout = 600
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/sergio/Documents/wallpaper
    fit_mode = cover
    timeout = 600
}
